services:
  proxy:
      build: .
      ports:
        - "8060:8060"
      depends_on:
        - auth
  
  db:
    #image: postgres:latest
    build: ./postgresdb
    environment:
      - POSTGRES_MULTIPLE_DATABASES=auth_ranking,subm_ranking
      #- POSTGRES_DB=auth_ranking
      - POSTGRES_USER=magisterbrownie
      - POSTGRES_PASSWORD=post
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=magisterbrownie --dbname=auth_ranking"]
      interval: 1s
      timeout: 5s
      retries: 5

  auth:
    build: auth/
    depends_on:
      db:
        condition: service_healthy

  api:
    build: ranking/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - auth

  
